---
# Install and setup a Dokuwiki!.
# Tested with: Ansible 2.2.1.
# Target host: Ubuntu 16.04.

- hosts: my_hosts

  vars_files:
  - vars.yml
  user: joe
  sudo: yes

  pre_tasks:
   - name: Update APT repositories. 
     apt: 
       update_cache: yes 
       cache_valid_time: 3600

  handlers:
    - name: restart apache
      service: 
        name: apache2
        state: restarted

  tasks:
   - name: Install Apache. 
     apt: 
       name: "{{ item }}"
       state: installed
       install_recommends: no

     vars:
       item:
       - apache2
       - php
       - libapache2-mod-php
       - php7.0-xml

   - name: Copy and extract dokuwiki files.
     unarchive:
      src: "{{ dokuwiki_file }}"
      dest: /var/www/html/

   - name: Setup necessary permissions for dokuwiki. 
     command: "{{item}}"
     with_items:
      - chown -R www-data:www-data "{{ dokuwiki_docroot }}" 
      - chmod 760 "{{ dokuwiki_docroot }}" 
      - find "{{ dokuwiki_docroot }}"/ -type d -exec chmod -c 0640 {} \; 
      - chmod -R ug+X "{{ dokuwiki_docroot }}"/ 
      - chmod -R g+w "{{ dokuwiki_docroot }}"/data/ "{{ dokuwiki_docroot }}"/conf/ "{{ dokuwiki_docroot }}"/lib/plugins/

   - name: Setup virtualhost for Dokuwiki. 
     template:
      src: "templates/dokuwiki.j2"
      dest: "/etc/apache2/sites-available/dokuwiki.conf"
      owner: root
      group: root
      mode: 0644
     notify: 
      - restart apache

   - name: Disable Apache default site and enable dokuwiki site.
     command: "{{item}}"
     with_items:
      - a2dissite 000-default
      - a2ensite dokuwiki 
     notify: 
      - restart apache    
