---
# Tested with Ansible 1.9.6
- hosts: test
  vars:
    pass: $5$NQTipd/a23R9m$Ll5s3eNq4ATurtghH6juMxhszDe6Cdows2S80IefgQB 
  user: root

  tasks:
  - name: Create a user
    user: 
      name: joe
      shell: /bin/bash
      createhome: yes
      password: "{{ pass }}"
      state: present
