---
# Tested with Ansible 1.9.6.
- hosts: test
  user: root
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
  tasks:
  - name: Disable Apache modules.
    apache2_module: 
      name={{ item }}
      state=absent
    with_items:
      - autoindex
      - cgi
    notify: restart apache
